import { ArrowRight, Braces, Database, GitBranch, ListChecks, Search } from "lucide-react";
import Link from "next/link";

import { PricingTable } from "./PricingTable";
import { RetrievalTrace } from "./RetrievalTrace";


export function LandingPage({ authEnabled }: { authEnabled: boolean }) {
  return (
    <div className="max-w-full overflow-x-hidden">
      <section className="border-b border-line">
        <div className="mx-auto max-w-7xl px-4 pb-14 pt-16 sm:px-6 sm:pb-20 sm:pt-24">
          <div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-end">
            <div className="min-w-0">
              <p className="text-sm font-semibold text-signal">Open source memory layer</p>
              <h1 className="mt-4 max-w-3xl text-4xl font-semibold leading-[1.08] text-ink sm:text-5xl lg:text-6xl">Memory infrastructure for AI products.</h1>
              <p className="mt-6 max-w-xl text-lg leading-8 text-muted">Store durable user context, retrieve the right memories, and inspect exactly what reaches the model.</p>
              <div className="mt-8 flex flex-wrap gap-3"><Link href={authEnabled ? "/sign-up" : "/docs"} className="rounded-md bg-signal px-4 py-2.5 text-sm font-semibold text-white hover:bg-signal/90 active:translate-y-px">Start free</Link><Link href="/docs" className="rounded-md border border-line bg-panel px-4 py-2.5 text-sm font-semibold hover:border-signal active:translate-y-px">View docs</Link></div>
            </div>
            <div className="min-w-0 overflow-hidden border-y border-line py-5"><div className="flex items-center justify-between gap-3"><span className="truncate font-mono text-xs text-muted">POST /v1/chat/completions</span><span className="shrink-0 rounded bg-tag px-2 py-1 font-mono text-[11px] text-signal">200 OK</span></div><p className="mt-5 text-sm leading-6 text-ink">OpenAI-compatible proxy, durable extraction, vector retrieval, and an audit trail in one request path.</p><div className="mt-5 grid grid-cols-1 gap-2 font-mono text-[11px] text-muted sm:grid-cols-3"><span>vector search</span><span>context injected</span><span>trace stored</span></div></div>
          </div>
          <div className="mt-12 min-w-0 max-w-full"><RetrievalTrace /></div>
        </div>
      </section>

      <section className="border-b border-line bg-panel"><div className="mx-auto grid max-w-7xl divide-y divide-line px-4 sm:px-6 md:grid-cols-3 md:divide-x md:divide-y-0"><Proof icon={Braces} title="OpenAI-compatible" text="Point an existing chat client at Engram's proxy without changing message shapes." /><Proof icon={GitBranch} title="MCP tools included" text="Search, add, update, list, and delete memories from compatible assistants." /><Proof icon={ListChecks} title="Every retrieval logged" text="Inspect the query, returned facts, similarity scores, and conversation ID." /></div></section>

      <section className="border-b border-line"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-sm font-semibold text-signal">One memory path</p><h2 className="mt-3 text-3xl font-semibold">Store. Retrieve. Inspect.</h2><p className="mt-4 text-base leading-7 text-muted">Engram keeps the memory lifecycle visible instead of burying it inside an agent framework.</p></div><ol className="divide-y divide-line border-y border-line"><Workflow number="01" title="Store durable facts" text="Extract useful user context asynchronously or add reviewed memories directly." icon={Database} /><Workflow number="02" title="Retrieve relevant context" text="Rank memories with pgvector, thresholds, namespaces, and optional graph expansion." icon={Search} /><Workflow number="03" title="Inspect what happened" text="Review memory state and retrieval logs before trusting assistant behavior." icon={ListChecks} /></ol></div></section>

      <section className="border-b border-line bg-panel"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><div className="mb-10 max-w-2xl"><p className="text-sm font-semibold text-signal">Operational, not opaque</p><h2 className="mt-3 text-3xl font-semibold">A ledger for facts. A trace for every lookup.</h2></div><div className="grid gap-6 lg:grid-cols-2"><ProductSurface title="Memory ledger" action="Review pending"><LedgerRow category="Preference" content="Prefers FastAPI for Python backends" status="Approved" /><LedgerRow category="Project" content="Building a self-hosted memory layer" status="Pending" /><LedgerRow category="Skill" content="Uses TypeScript for frontend work" status="Approved" /></ProductSurface><ProductSurface title="Retrieval log" action="Open trace"><LogRow query="What stack should I use?" count="2 memories" score="0.91 top score" /><LogRow query="How should deployment stay inexpensive?" count="3 memories" score="0.87 top score" /><LogRow query="Which frontend patterns were rejected?" count="2 memories" score="0.82 top score" /></ProductSurface></div></div></section>

      <section className="border-b border-line"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold text-signal">Small integration surface</p><h2 className="mt-3 text-3xl font-semibold">Keep your client. Add memory.</h2><p className="mt-4 text-base leading-7 text-muted">Use the REST API, the compatible chat endpoint, or the MCP server. Provider credentials stay under your control.</p><Link href="/docs" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-signal hover:underline">Read the integration guide <ArrowRight size={15} /></Link></div><pre className="min-w-0 overflow-x-auto border border-line bg-panel p-5 font-mono text-xs leading-6 text-muted"><code>{`curl http://localhost:8000/v1/chat/completions \\\n  -H "Authorization: Bearer $ENGRAM_KEY" \\\n  -H "X-Engram-Provider: openai" \\\n  -d '{\n    "model": "gpt-4o-mini",\n    "messages": [{"role":"user","content":"..."}]\n  }'`}</code></pre></div></section>

      <section id="pricing" className="border-b border-line bg-paper"><div className="mx-auto max-w-5xl px-4 py-16 sm:px-6 sm:py-24"><div className="mb-10"><p className="text-sm font-semibold text-signal">Pricing</p><h2 className="mt-3 text-3xl font-semibold">Pay for the memory layer, not marked-up model tokens.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-muted">Both plans use your provider key. Hosted Engram does not add model credits or a hidden inference margin.</p></div><PricingTable authEnabled={authEnabled} /></div></section>

      <section className="border-b border-line bg-panel"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-2"><div><p className="text-sm font-semibold text-signal">Self-host when you need to</p><h2 className="mt-3 text-3xl font-semibold">FastAPI, Postgres, pgvector, and no proprietary vector store.</h2></div><div className="space-y-4 text-base leading-7 text-muted"><p>Run the same API, dashboard, and MCP server with Docker Compose. Your memory data stays in PostgreSQL.</p><div className="flex gap-3"><a href="https://github.com/macayu17/engram" className="rounded-md border border-line px-4 py-2 text-sm font-semibold text-ink hover:border-signal">View GitHub</a><Link href="/docs" className="rounded-md border border-line px-4 py-2 text-sm font-semibold text-ink hover:border-signal">Self-hosting docs</Link></div></div></div></section>

      <section><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[0.65fr_1.35fr]"><div><p className="text-sm font-semibold text-signal">FAQ</p><h2 className="mt-3 text-3xl font-semibold">Before you connect a model</h2></div><div className="divide-y divide-line border-y border-line"><Faq question="Does Engram pay for model usage?" answer="No. Hosted workspaces bring their own OpenAI, Anthropic, Gemini, or Ollama provider configuration." /><Faq question="Can retrieval failures break a chat request?" answer="No. Engram logs retrieval failures and forwards the original request without injected memories." /><Faq question="Can I inspect and delete memories?" answer="Yes. The dashboard and API expose review, edit, export, merge, and deletion workflows." /><Faq question="Is the MCP server optional?" answer="Yes. Use REST, the compatible proxy, MCP, or all three against the same memory store." /></div></div></section>
    </div>
  );
}

function Proof({ icon: Icon, title, text }: { icon: typeof Braces; title: string; text: string }) { return <div className="flex gap-4 py-6 md:px-6"><Icon className="mt-0.5 shrink-0 text-signal" size={19} strokeWidth={1.8} /><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{text}</p></div></div>; }
function Workflow({ number, title, text, icon: Icon }: { number: string; title: string; text: string; icon: typeof Database }) { return <li className="grid gap-3 py-6 sm:grid-cols-[3rem_2rem_1fr] sm:items-start"><span className="font-mono text-xs text-muted">{number}</span><Icon size={19} className="text-signal" strokeWidth={1.8} /><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{text}</p></div></li>; }
function ProductSurface({ title, action, children }: { title: string; action: string; children: React.ReactNode }) { return <section className="border border-line bg-paper"><div className="flex items-center justify-between border-b border-line px-4 py-3"><h3 className="text-sm font-semibold">{title}</h3><span className="text-xs text-signal">{action}</span></div><div className="divide-y divide-line">{children}</div></section>; }
function LedgerRow({ category, content, status }: { category: string; content: string; status: string }) { return <div className="grid gap-2 px-4 py-4 sm:grid-cols-[6rem_1fr_auto] sm:items-center"><span className="text-xs text-muted">{category}</span><span className="text-sm text-ink">{content}</span><span className={status === "Pending" ? "text-xs text-caution" : "text-xs text-signal"}>{status}</span></div>; }
function LogRow({ query, count, score }: { query: string; count: string; score: string }) { return <div className="grid gap-2 px-4 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><span className="text-sm text-ink">{query}</span><span className="font-mono text-xs text-muted">{count} · {score}</span></div>; }
function Faq({ question, answer }: { question: string; answer: string }) { return <details className="group py-5"><summary className="cursor-pointer list-none pr-8 text-base font-semibold text-ink">{question}</summary><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{answer}</p></details>; }
